version: '3.5'

services:
  desafio-mysql:
    image: mysql:8.0.1
    container_name: desafio-mysql
    environment: 
       MYSQL_ROOT_PASSWORD: "123"
       TZ: America/Manaus
    ports:
       - '3306:3306'
    volumes:
       - db:/var/lib/mysql
    networks:
      - mysql-network     
  desafio-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: desafio-phpmyadmin
    ports:
       - 8081:80
    links: 
      - desafio-mysql:db
  backend: 
    container_name: 'web-api'
    command: npm run dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./web-api:/usr/app      
    networks:
      - mysql-network
    depends_on:
      - desafio-mysql  
  web-server:
    image: quay.io/vesica/php73:latest
    container_name: web-server
    volumes:
      - ./www:/var/www
    ports:
      - 80:80
    networks:
      - mysql-network
     

networks:
  mysql-network:
    driver: bridge

volumes:
    db:
    desafio-phpmyadmin: